[workspace]
members = [
    "opentelemetry",
    "opentelemetry-contrib",
    "opentelemetry-jaeger",
    "opentelemetry-otlp",
    "opentelemetry-prometheus",
    "opentelemetry-semantic-conventions",
    "opentelemetry-zipkin",
    "examples/actix-udp",
    "examples/actix-http",
    "examples/async",
    "examples/aws-xray",
    "examples/basic",
    "examples/basic-otlp",
    "examples/datadog",
    "examples/grpc",
    "examples/http",
    "examples/zipkin",
    "examples/tracing-grpc"
]
